name: category
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: pip install -r ./requirements.txt --target ./lambda
    - name: Deploy code to Lambda
      uses: Rakeshgombi/category@v1.0.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-1:462252041108:function:category'
        lambda_function_name: 'category'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'


